pub const INDEX_DIR: &str = ".knowledge-loom-index";
pub const BIN_DIR: &str = ".knowledge-loom/bin";
pub const IGNORE_FILE: &str = ".knowledge-loom-ignore";
pub const MCP_CONFIG_KEY: &str = "knowledge-loom";
pub const GITIGNORE_ENTRY_BIN: &str = ".knowledge-loom/";
pub const GITIGNORE_ENTRY_INDEX: &str = ".knowledge-loom-index/";

pub mod cli;
pub mod bm25;
pub mod chunks;
pub mod daemon;
pub mod download;
pub mod edits;
pub mod embed;
pub mod graph;
pub mod index;
pub mod init;
pub mod install;
pub mod maintenance;
pub mod model;
pub mod platforms;
pub mod search;
pub mod server;
pub mod shell;
pub mod vault;
pub mod web;
