// src/shell.rs
use std::process::Stdio;
use tokio::process::Command;

/// Generate a standalone shell script that starts the server and drops into a shell.
pub fn make_shell_script(binary_path: &str, kb_root: &str) -> String {
    format!(
        r#"#!/bin/sh
# Generated by knowledge-loom init
# Starts the loom MCP server and opens an interactive shell.
export KB_ROOT="{kb_root}"
"{binary_path}" serve &
LOOM_PID=$!
trap "kill $LOOM_PID 2>/dev/null" EXIT INT TERM
exec ${{SHELL:-/bin/sh}}
"#
    )
}

/// Run the loom MCP server in a background task, then exec the user's shell.
/// On shell exit, the server task is aborted.
pub async fn run_shell() -> Result<(), Box<dyn std::error::Error>> {
    // Determine KB_ROOT
    let kb_root = std::env::var("KB_ROOT")
        .unwrap_or_else(|_| std::env::current_dir()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_else(|_| ".".to_string()));

    eprintln!("knowledge-loom shell — KB_ROOT={kb_root}");
    eprintln!("Starting MCP server in background...");

    // Start server as background task
    std::env::set_var("KB_ROOT", &kb_root);
    let server_handle = tokio::spawn(async move {
        crate::server::run_server().await;
    });

    // Give server a moment to initialize
    tokio::time::sleep(tokio::time::Duration::from_millis(200)).await;

    // Spawn user's shell
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/sh".to_string());
    eprintln!("Dropping into {shell} — exit to stop the server.");

    let status = Command::new(&shell)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .await?;

    server_handle.abort();
    eprintln!("knowledge-loom shell exited.");

    std::process::exit(status.code().unwrap_or(0));
}
